name: rodio_scheduler Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Checks for rustc nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install alsa libs
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev
      
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - name: Run cargo check
        run: cargo check
  
  test:
    name: Tests for rustc nightly on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install alsa libs
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev
    
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal

    - name: Run cargo build (debug)
      run: cargo build --verbose
    - name: Run cargo test (debug)
      run: cargo test --verbose
    - name: Run cargo build (release)
      run: cargo build --release --verbose
    - name: Run cargo test (release)
      run: cargo test --release --verbose
